# Generated by Django 5.0.4 on 2024-05-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='lastName',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='birthDate',
            new_name='birth_Date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_Name',
        ),
    ]
