# Generated by Django 5.0.4 on 2024-06-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_firstname_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lecturer',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
