# Generated by Django 5.0.4 on 2024-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_admin_profile_pic_lecturer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/'),
        ),
    ]
