# Generated by Django 5.0.4 on 2024-06-20 10:08

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_admin_profile_pic_alter_lecturer_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to=main.models.upload_path),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to=main.models.upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/default.png', upload_to=main.models.upload_path),
        ),
    ]
