# Generated by Django 5.0.4 on 2024-06-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_admin_profile_pic_alter_lecturer_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
