# Generated by Django 5.0.4 on 2024-06-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='address',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phoen_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
