# Generated by Django 5.0.4 on 2024-06-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_lecturer_address_lecturer_phoen_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='phoen_number',
            new_name='phone_number',
        ),
    ]
