# Generated by Django 5.0.4 on 2024-06-24 14:25

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_course_lecturer_id_remove_student_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course_images/default.png', upload_to=main.models.upload_path_course),
        ),
    ]
