# Generated by Django 5.0.4 on 2024-06-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender_id',
            new_name='lecturer_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='receiver_id',
            new_name='student_id',
        ),
    ]
