# Generated by Django 5.0.4 on 2024-06-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_phone_number_lecturer_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='lecturecourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='lecturecourse',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='lectureravailability',
            name='lecture_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='student_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='LectureCourse',
        ),
        migrations.DeleteModel(
            name='LecturerAvailability',
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
