# Generated by Django 5.0.4 on 2024-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_lecturematerial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
