# Generated by Django 5.0.4 on 2024-06-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_lecturematerial_filename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatGPT',
            new_name='EduAI',
        ),
    ]
