# Generated by Django 5.0.6 on 2024-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
    ]
